version: "5.0"

services:
  wordpress:
    container_name: ${PROJECT_ID}
    image: wordpress:6.8
    user: "www-data:www-data"
    restart: unless-stopped
    networks:
      - webnet
    environment:
      WORDPRESS_DB_HOST: mysql # Connects to your shared DB container
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}

    volumes:
      # Application Source Code
      - ./src/.htaccess:/var/www/html/.htaccess
      - ./src/wp-content/themes:/var/www/html/wp-content/themes
      - ./src/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./src/wp-content/uploads:/var/www/html/wp-content/uploads
      
      # Exclude default WP content to save space
      - /var/www/html/wp-content/themes/twentytwentyone/
      - /var/www/html/wp-content/themes/twentytwentytwo/
      - /var/www/html/wp-content/themes/twentytwentythree/
      - /var/www/html/wp-content/themes/twentytwentyfour/
      - /var/www/html/wp-content/themes/twentytwentyfive/

networks:
  webnet:
    external: true
